 server:
  port: 9000
 spring:
  application:
    name: air-gateway
 eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
 ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000 
 zuul:
  host: 
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    pad:
      path: /pad/**
      service-id: air-pad-service
    device:
      path: /device/**
      service-id: air-device-service
    order:
      path: /order/**
      service-id: air-order-service      
    space:
      path: /space/**
      service-id: air-space-service 
    room:
      path: /room/**
      service-id: air-room-service       
    front:
      path: /front/**
      service-id: air-front-service       
    sys:
      path: /sys/**
      service-id: air-sys-service
    token:
      path: /token/**
      service-id: air-token-service
    tools:
      path: /tools/**
      service-id: air-tools-service                         

 spring:
  application:
    name: air-gateway      
  profiles:
    active:
    - local    
    
---

 spring:
  profiles: local    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/          
---
spring:
  profiles: remote17
eureka:
  instance:
    hostname: 172.21.32.17
  client:
    serviceUrl:
      defaultZone: http://172.21.32.3:8761/eureka/      
        
